/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import transaksi.jual;
import koneksi.koneksi;
/**
 *
 * @author Asus
 */
public class popupkaryawan extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;

public jual karyawan = null;
    /**
     * Creates new form popupkaryawan
     */
    public popupkaryawan() {
        initComponents();
        datatable();
    }
    
    protected void datatable(){
        Object[] Baris ={"NIK","Nama Karyawan","Jabatan","No. Handphone","Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem=txtcaripopupkaryawan.getText();
        try {
            String sql = "SELECT * FROM karyawan where nik like '%"+cariitem+"%' or nmkaryawan like '%"+cariitem+"%' order by nik asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5)
                });
            }
            tblpopupkaryawan.setModel(tabmode);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcaripopupkaryawan = new javax.swing.JTextField();
        bcaripopupkaryawan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpopupkaryawan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pop Up Data Kasir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcaripopupkaryawan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcaripopupkaryawan.setToolTipText("");
        txtcaripopupkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaripopupkaryawanActionPerformed(evt);
            }
        });
        txtcaripopupkaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaripopupkaryawanKeyPressed(evt);
            }
        });
        jPanel2.add(txtcaripopupkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, 110, -1));

        bcaripopupkaryawan.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bcaripopupkaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_30p.png"))); // NOI18N
        bcaripopupkaryawan.setText("Cari");
        bcaripopupkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaripopupkaryawanActionPerformed(evt);
            }
        });
        jPanel2.add(bcaripopupkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 18, -1, -1));

        tblpopupkaryawan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblpopupkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpopupkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpopupkaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpopupkaryawan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 110));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA KASIR");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcaripopupkaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaripopupkaryawanKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcaripopupkaryawanKeyPressed

    private void bcaripopupkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaripopupkaryawanActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcaripopupkaryawanActionPerformed

    private void tblpopupkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpopupkaryawanMouseClicked
        // TODO add your handling code here:
        int tabelkaryawan=tblpopupkaryawan.getSelectedRow();
        karyawan.nik = tblpopupkaryawan.getValueAt(tabelkaryawan, 0).toString();
        karyawan.nmkaryawan = tblpopupkaryawan.getValueAt(tabelkaryawan, 1).toString();
        karyawan.jabatan = tblpopupkaryawan.getValueAt(tabelkaryawan, 2).toString();
        karyawan.nohpk = tblpopupkaryawan.getValueAt(tabelkaryawan, 3).toString();
        karyawan.alamatk = tblpopupkaryawan.getValueAt(tabelkaryawan, 4).toString();
        karyawan.itemTerpilihkaryawan();
        this.dispose();
    }//GEN-LAST:event_tblpopupkaryawanMouseClicked

    private void txtcaripopupkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaripopupkaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaripopupkaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popupkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popupkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popupkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popupkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popupkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcaripopupkaryawan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpopupkaryawan;
    private javax.swing.JTextField txtcaripopupkaryawan;
    // End of variables declaration//GEN-END:variables
}
