/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package popup;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import transaksi.beli;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class popupsupplier extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;

public beli supplier = null;
    /**
     * Creates new form popupsupplier
     */
    public popupsupplier() {
        initComponents();
        datatable();
    }
    
    protected void datatable(){
        Object[] Baris ={"ID Supplier","Nama Supplier","No. Handphone","Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem=txtcaripopupsupplier.getText();
        try {
            String sql = "SELECT * FROM supplier where idsupplier like '%"+cariitem+"%' or nmsupplier like '%"+cariitem+"%' order by idsupplier asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4)
                });
            }
            tblpopupsupplier.setModel(tabmode);
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcaripopupsupplier = new javax.swing.JTextField();
        bcaripopupsupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpopupsupplier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pop Up Data Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcaripopupsupplier.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcaripopupsupplier.setToolTipText("");
        txtcaripopupsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcaripopupsupplierActionPerformed(evt);
            }
        });
        txtcaripopupsupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaripopupsupplierKeyPressed(evt);
            }
        });
        jPanel2.add(txtcaripopupsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, 110, -1));

        bcaripopupsupplier.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bcaripopupsupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_30p.png"))); // NOI18N
        bcaripopupsupplier.setText("Cari");
        bcaripopupsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaripopupsupplierActionPerformed(evt);
            }
        });
        jPanel2.add(bcaripopupsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 18, -1, -1));

        tblpopupsupplier.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblpopupsupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpopupsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpopupsupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpopupsupplier);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 110));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA SUPPLIER");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcaripopupsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcaripopupsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcaripopupsupplierActionPerformed

    private void txtcaripopupsupplierKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaripopupsupplierKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcaripopupsupplierKeyPressed

    private void bcaripopupsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaripopupsupplierActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcaripopupsupplierActionPerformed

    private void tblpopupsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpopupsupplierMouseClicked
        // TODO add your handling code here:
        int tabelsupplier=tblpopupsupplier.getSelectedRow();
        supplier.idsupplier = tblpopupsupplier.getValueAt(tabelsupplier, 0).toString();
        supplier.nmsupplier = tblpopupsupplier.getValueAt(tabelsupplier, 1).toString();
        supplier.nohps = tblpopupsupplier.getValueAt(tabelsupplier, 2).toString();
        supplier.alamats = tblpopupsupplier.getValueAt(tabelsupplier, 3).toString();
        supplier.itemTerpilihsupplier();
        this.dispose();
    }//GEN-LAST:event_tblpopupsupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popupsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popupsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popupsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popupsupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popupsupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcaripopupsupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblpopupsupplier;
    private javax.swing.JTextField txtcaripopupsupplier;
    // End of variables declaration//GEN-END:variables
}
