/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class karyawan extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form karyawan
     */
    public karyawan() {
        initComponents();
        kosong();
        aktif();
        datatable();
        autonumber();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    
    protected void aktif(){
    txtnmk.requestFocus();
    cbjabatan.setSelectedItem("Item1");
    }
    
    protected void kosong(){
    txtnmk.setText("");
    cbjabatan.setSelectedItem("-Pilih Jabatan-");
    txthpk.setText("");
    txtalamatk.setText("");
    txtcarik.setText("");
    }
    
    protected void datatable(){
    Object[] Baris ={"NIK","Nama Karyawan","Jabatan","No. Handphone","Alamat"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem=txtcarik.getText();

    try {
        String sql = "SELECT * FROM karyawan where nik like '%"+cariitem+"%' or nmkaryawan like '%"+cariitem+"%' order by nik asc";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
        tabmode.addRow(new Object[]{
        hasil.getString(1),
        hasil.getString(2),
        hasil.getString(3),
        hasil.getString(4),
        hasil.getString(5)
        });
    }
        tblkaryawan.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    
    protected void autonumber(){
        try {
            String sql = "SELECT nik FROM karyawan order by nik asc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            txtnik.setText("KRY0001");
            while (rs.next()) {
                String id_karyawan = rs.getString("nik").substring(3);
                int AN = Integer.parseInt(id_karyawan) + 1;
                String Nol = ""; 
 
                  if(AN<10)
                  {Nol = "000";}
                  else if(AN<100)
                  {Nol = "00";}
                  else if(AN<1000)
                  {Nol = "0";}
                  else if(AN<10000)
                  {Nol = "";} 
 
                  txtnik.setText("KRY" + Nol + AN);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Auto Number Gagal" +e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnmk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbjabatan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txthpk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatk = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblkaryawan = new javax.swing.JTable();
        txtcarik = new javax.swing.JTextField();
        bcarik = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bsimpank = new javax.swing.JButton();
        bubahk = new javax.swing.JButton();
        bhapusk = new javax.swing.JButton();
        bbatalk = new javax.swing.JButton();
        bkeluark = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(630, 580));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(630, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA KARYAWAN");
        jLabel1.setToolTipText("");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Karyawan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("NIK");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        txtnik.setEditable(false);
        txtnik.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Nama Karyawan");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        txtnmk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(txtnmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 155, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Jabatan");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        cbjabatan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Jabatan-", "Pemilik", "Admin", "Pramuniaga", "Bagian Gudang" }));
        jPanel3.add(cbjabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("No. Handphone");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, -1, -1));

        txthpk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(txthpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 155, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Alamat");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(184, 74));

        txtalamatk.setColumns(20);
        txtalamatk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtalamatk.setRows(5);
        jScrollPane1.setViewportView(txtalamatk);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 200, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 330, 320));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Karyawan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tblkaryawan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblkaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblkaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblkaryawanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblkaryawan);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 110));

        txtcarik.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcarik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarikKeyPressed(evt);
            }
        });
        jPanel4.add(txtcarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, 97, -1));

        bcarik.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bcarik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_30p.png"))); // NOI18N
        bcarik.setText("Cari");
        bcarik.setToolTipText("");
        bcarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcarikActionPerformed(evt);
            }
        });
        jPanel4.add(bcarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 17, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 600, 190));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpank.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bsimpank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save_30px.png"))); // NOI18N
        bsimpank.setText("Simpan");
        bsimpank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpankActionPerformed(evt);
            }
        });
        jPanel5.add(bsimpank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, -1));

        bubahk.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bubahk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_30px.png"))); // NOI18N
        bubahk.setText("Ubah");
        bubahk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahkActionPerformed(evt);
            }
        });
        jPanel5.add(bubahk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        bhapusk.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bhapusk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus_30px.png"))); // NOI18N
        bhapusk.setText("Hapus");
        bhapusk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapuskActionPerformed(evt);
            }
        });
        jPanel5.add(bhapusk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        bbatalk.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bbatalk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancelit_30px.png"))); // NOI18N
        bbatalk.setText("Batal");
        bbatalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalkActionPerformed(evt);
            }
        });
        jPanel5.add(bbatalk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        bkeluark.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bkeluark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exitsign_30px.png"))); // NOI18N
        bkeluark.setText("Keluar");
        bkeluark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarkActionPerformed(evt);
            }
        });
        jPanel5.add(bkeluark, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, 270));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/HOME.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bsimpankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpankActionPerformed
        // TODO add your handling code here:
        String sql = "insert into karyawan values (?,?,?,?,?)";
         try {
             PreparedStatement stat = conn.prepareStatement(sql);
             stat.setString(1,txtnik.getText());
             stat.setString(2,txtnmk.getText());
             stat.setString(3,cbjabatan.getSelectedItem().toString());
             stat.setString(4,txthpk.getText());
             stat.setString(5,txtalamatk.getText());
             
             stat.executeUpdate();
             JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
             kosong();
             autonumber();
             txtnmk.requestFocus();
         }
         catch (SQLException e) {
             JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
         }
         datatable();   
    }//GEN-LAST:event_bsimpankActionPerformed

    private void bubahkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahkActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "update karyawan set nmkaryawan=?,jabatan=?,nohpk=?,alamatk=? where nik ='"+txtnik.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,txtnmk.getText());
            stat.setString(2,cbjabatan.getSelectedItem().toString());
            stat.setString(3,txthpk.getText());
            stat.setString(4,txtalamatk.getText());
 
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            autonumber();
            txtnmk.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
        }
        datatable(); 

    }//GEN-LAST:event_bubahkActionPerformed

    private void bhapuskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapuskActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
         if (ok==0){
             String sql = "delete from karyawan where nik ='"+txtnik.getText()+"'";
             try{
                 PreparedStatement stat = conn.prepareStatement(sql);
                 stat.executeUpdate();
                 JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                 kosong();
                 autonumber();
                 txtnmk.requestFocus();
             }
             catch (SQLException e){
                 JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e);
             }
             datatable();
         }
    }//GEN-LAST:event_bhapuskActionPerformed

    private void bbatalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalkActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
        autonumber();
    }//GEN-LAST:event_bbatalkActionPerformed

    private void bkeluarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarkActionPerformed
        // TODO add your handling code here:
        dispose();
        new start.home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bkeluarkActionPerformed

    private void tblkaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkaryawanMouseClicked
        // TODO add your handling code here:
        int bar=tblkaryawan.getSelectedRow();
        String a = tabmode.getValueAt(bar,0).toString();
        String b = tabmode.getValueAt(bar,1).toString();
        String c = tabmode.getValueAt(bar,2).toString();
        String d = tabmode.getValueAt(bar,3).toString();
        String e = tabmode.getValueAt(bar,4).toString();

            txtnik.setText(a);
            txtnmk.setText(b);
            cbjabatan.setSelectedItem(c);
            txthpk.setText(d);
            txtalamatk.setText(e);
    }//GEN-LAST:event_tblkaryawanMouseClicked

    private void bcarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcarikActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcarikActionPerformed

    private void txtcarikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarikKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        datatable();
        }
    }//GEN-LAST:event_txtcarikKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatalk;
    private javax.swing.JButton bcarik;
    private javax.swing.JButton bhapusk;
    private javax.swing.JButton bkeluark;
    private javax.swing.JButton bsimpank;
    private javax.swing.JButton bubahk;
    private javax.swing.JComboBox<String> cbjabatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblkaryawan;
    private javax.swing.JTextArea txtalamatk;
    private javax.swing.JTextField txtcarik;
    private javax.swing.JTextField txthpk;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnmk;
    // End of variables declaration//GEN-END:variables
}
