/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import koneksi.koneksi;
/**
 *
 * @author Asus
 */
public class pelanggan extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form pelanggan
     */
    public pelanggan() {
        initComponents();
        kosong();
        aktif();
        datatable();
        autonumber();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    
    protected void aktif(){
    txtnmp.requestFocus();
    }
    
    protected void kosong(){
    txtnmp.setText("");
    txthpp.setText("");
    txtalamatp.setText("");
    txtcarip.setText("");
    buttonGroup1.clearSelection();
    }
    
    protected void datatable(){
    Object[] Baris ={"ID Pelanggan","Nama Pelanggan","Jenis Kelamin","No. Handphone","Alamat"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem=txtcarip.getText();

    try {
        String sql = "SELECT * FROM pelanggan where idpelanggan like '%"+cariitem+"%' or nmpelanggan like '%"+cariitem+"%' order by idpelanggan asc";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
        tabmode.addRow(new Object[]{
        hasil.getString(1),
        hasil.getString(2),
        hasil.getString(3),
        hasil.getString(4),
        hasil.getString(5)
        });
    }
        tblpelanggan.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    
    protected void autonumber(){
        try {
            String sql = "SELECT idpelanggan FROM pelanggan order by idpelanggan asc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            txtid.setText("IN0001");
            while (rs.next()) {
                String id_pelanggan = rs.getString("idpelanggan").substring(2);
                int AN = Integer.parseInt(id_pelanggan) + 1;
                String Nol = ""; 
 
                  if(AN<10)
                  {Nol = "000";}
                  else if(AN<100)
                  {Nol = "00";}
                  else if(AN<1000)
                  {Nol = "0";}
                  else if(AN<10000)
                  {Nol = "";} 
 
                  txtid.setText("IN" + Nol + AN);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Auto Number Gagal" +e);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnmp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rlaki = new javax.swing.JRadioButton();
        rperempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txthpp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatp = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        bsimpanp = new javax.swing.JButton();
        bubahp = new javax.swing.JButton();
        bhapusp = new javax.swing.JButton();
        bbatalp = new javax.swing.JButton();
        bkeluarp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpelanggan = new javax.swing.JTable();
        txtcarip = new javax.swing.JTextField();
        bcarip = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA PELANGGAN");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("ID Pelanggan");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        txtid.setEditable(false);
        txtid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtid.setToolTipText("");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel3.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Nama Pelanggan");
        jLabel3.setToolTipText("");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        txtnmp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtnmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmpActionPerformed(evt);
            }
        });
        jPanel3.add(txtnmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 155, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, -1, -1));

        buttonGroup1.add(rlaki);
        rlaki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rlaki.setText("Laki-Laki");
        jPanel3.add(rlaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        buttonGroup1.add(rperempuan);
        rperempuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rperempuan.setText("Perempuan");
        jPanel3.add(rperempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("No. Handphone");
        jLabel5.setToolTipText("");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, -1, -1));

        txthpp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txthpp.setToolTipText("");
        txthpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthppActionPerformed(evt);
            }
        });
        jPanel3.add(txthpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 155, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Alamat");
        jLabel6.setToolTipText("");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, -1));

        txtalamatp.setColumns(20);
        txtalamatp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtalamatp.setRows(5);
        jScrollPane1.setViewportView(txtalamatp);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 110));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 320, 320));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpanp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bsimpanp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save_30px.png"))); // NOI18N
        bsimpanp.setText("Simpan");
        bsimpanp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanpActionPerformed(evt);
            }
        });
        jPanel4.add(bsimpanp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, -1));

        bubahp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bubahp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_30px.png"))); // NOI18N
        bubahp.setText("Ubah");
        bubahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahpActionPerformed(evt);
            }
        });
        jPanel4.add(bubahp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        bhapusp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bhapusp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus_30px.png"))); // NOI18N
        bhapusp.setText("Hapus");
        bhapusp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapuspActionPerformed(evt);
            }
        });
        jPanel4.add(bhapusp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        bbatalp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bbatalp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancelit_30px.png"))); // NOI18N
        bbatalp.setText("Batal");
        bbatalp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalpActionPerformed(evt);
            }
        });
        jPanel4.add(bbatalp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        bkeluarp.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bkeluarp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exitsign_30px.png"))); // NOI18N
        bkeluarp.setText("Keluar");
        bkeluarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarpActionPerformed(evt);
            }
        });
        jPanel4.add(bkeluarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 130, 270));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblpelanggan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblpelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpelanggan);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 570, 110));

        txtcarip.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcarip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcaripKeyPressed(evt);
            }
        });
        jPanel5.add(txtcarip, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, 97, -1));

        bcarip.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bcarip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_30p.png"))); // NOI18N
        bcarip.setText("Cari");
        bcarip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaripActionPerformed(evt);
            }
        });
        jPanel5.add(bcarip, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 17, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 600, 200));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/HOME.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthppActionPerformed

    private void bsimpanpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanpActionPerformed
        // TODO add your handling code here:
        String jenis = null;
        if(rlaki.isSelected()){
        jenis = "Laki-Laki";
        }else if(rperempuan.isSelected()){
        jenis = "Perempuan";
        }
            String sql = "insert into pelanggan values (?,?,?,?,?)";
    try{
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtid.getText());
        stat.setString(2, txtnmp.getText());
        stat.setString(3, jenis);
        stat.setString(4, txthpp.getText());
        stat.setString(5, txtalamatp.getText());

        stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        kosong();
        autonumber();
        txtnmp.requestFocus();
    } catch (SQLException e){
        JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
    }
        datatable();
    }//GEN-LAST:event_bsimpanpActionPerformed

    private void txtnmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmpActionPerformed

    private void bubahpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahpActionPerformed
        // TODO add your handling code here:
        String jenis = null;
        if(rlaki.isSelected()){
        jenis = "Laki-Laki";
        }else if(rperempuan.isSelected()){
        jenis = "Perempuan";
        }
    try{
        String sql = "update pelanggan set nmpelanggan=?,jenis=?,nohp=?,alamat=? where idpelanggan='"+txtid.getText()+"'";
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtnmp.getText());
        stat.setString(2, jenis);
        stat.setString(3, txthpp.getText());
        stat.setString(4, txtalamatp.getText());
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "data berhasil diubah");
        kosong();
        autonumber();
        txtnmp.requestFocus();
    }
       catch (SQLException e){
        JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
    }
    datatable();
    }//GEN-LAST:event_bubahpActionPerformed

    private void bhapuspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapuspActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus","konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
            if (ok==0){
                String sql = "delete from pelanggan where idpelanggan ='"+txtid.getText()+"'";
    try{
        PreparedStatement stat = conn.prepareStatement(sql);
        stat.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        kosong();
        autonumber();
        txtnmp.requestFocus();
    }
        catch (SQLException e){
        JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e);
    }
        datatable();
    }
    }//GEN-LAST:event_bhapuspActionPerformed

    private void bbatalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalpActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalpActionPerformed

    private void bkeluarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarpActionPerformed
        // TODO add your handling code here:
        dispose();
        new start.home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bkeluarpActionPerformed

    private void tblpelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpelangganMouseClicked
        // TODO add your handling code here:
        int bar = tblpelanggan.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();

            txtid.setText(a);
            txtnmp.setText(b);
            if ("Laki-Laki".equals(c)) {
            rlaki.setSelected(true);
            } else{
            rperempuan.setSelected(true);
            }
    txthpp.setText(d);
    txtalamatp.setText(e);

    }//GEN-LAST:event_tblpelangganMouseClicked

    private void bcaripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaripActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcaripActionPerformed

    private void txtcaripKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcaripKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        datatable();
        }
    }//GEN-LAST:event_txtcaripKeyPressed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatalp;
    private javax.swing.JButton bcarip;
    private javax.swing.JButton bhapusp;
    private javax.swing.JButton bkeluarp;
    private javax.swing.JButton bsimpanp;
    private javax.swing.JButton bubahp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rlaki;
    private javax.swing.JRadioButton rperempuan;
    private javax.swing.JTable tblpelanggan;
    private javax.swing.JTextArea txtalamatp;
    private javax.swing.JTextField txtcarip;
    private javax.swing.JTextField txthpp;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnmp;
    // End of variables declaration//GEN-END:variables
}
