/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package master;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import koneksi.koneksi;

/**
 *
 * @author Asus
 */
public class supllier extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form supllier
     */
    public supllier() {
        initComponents();
        kosong();
        aktif();
        datatable();
        autonumber();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    
    protected void aktif(){
    txtnms.requestFocus();
    }

    protected void kosong(){
    txtnms.setText("");
    txthps.setText("");
    txtalamats.setText("");
    txtcaris.setText("");
    }
    
    protected void datatable(){
    Object[] Baris ={"ID Supplier","Nama Supplier","No. Handphone","Alamat"};
    tabmode = new DefaultTableModel(null, Baris);
    String cariitem=txtcaris.getText();

    try {
        String sql = "SELECT * FROM supplier where idsupplier like '%"+cariitem+"%' or nmsupplier like '%"+cariitem+"%' order by idsupplier asc";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
        tabmode.addRow(new Object[]{
        hasil.getString(1),
        hasil.getString(2),
        hasil.getString(3),
        hasil.getString(4)
        });
    }
        tblsupplier.setModel(tabmode);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    
    protected void autonumber(){
        try {
            String sql = "SELECT idsupplier FROM supplier order by idsupplier asc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            txtids.setText("SPL0001");
            while (rs.next()) {
                String id_supplier = rs.getString("idsupplier").substring(3);
                int AN = Integer.parseInt(id_supplier) + 1;
                String Nol = ""; 
 
                  if(AN<10)
                  {Nol = "000";}
                  else if(AN<100)
                  {Nol = "00";}
                  else if(AN<1000)
                  {Nol = "0";}
                  else if(AN<10000)
                  {Nol = "";} 
 
                  txtids.setText("SPL" + Nol + AN);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Auto Number Gagal" +e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtids = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnms = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txthps = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamats = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblsupplier = new javax.swing.JTable();
        txtcaris = new javax.swing.JTextField();
        bcaris = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bsimpans = new javax.swing.JButton();
        bubahs = new javax.swing.JButton();
        bhapuss = new javax.swing.JButton();
        bbatals = new javax.swing.JButton();
        bkeluars = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(java.awt.Color.red);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("DATA SUPPLIER");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel2.setText("ID Supplier");
        jLabel2.setToolTipText("");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, -1));

        txtids.setEditable(false);
        txtids.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(txtids, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel3.setText("Nama Supplier");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        txtnms.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(txtnms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 155, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel5.setText("No. Handphone");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 113, -1, -1));

        txthps.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel3.add(txthps, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 155, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jLabel6.setText("Alamat");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(184, 74));

        txtalamats.setColumns(20);
        txtalamats.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtalamats.setRows(5);
        jScrollPane1.setViewportView(txtalamats);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 200, 120));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 330, 290));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tblsupplier.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblsupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsupplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblsupplier);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 110));

        txtcaris.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtcaris.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarisKeyPressed(evt);
            }
        });
        jPanel4.add(txtcaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, 97, -1));

        bcaris.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bcaris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_30p.png"))); // NOI18N
        bcaris.setText("Cari");
        bcaris.setToolTipText("");
        bcaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcarisActionPerformed(evt);
            }
        });
        jPanel4.add(bcaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 17, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 600, 190));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 11))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bsimpans.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bsimpans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/save_30px.png"))); // NOI18N
        bsimpans.setText("Simpan");
        bsimpans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpansActionPerformed(evt);
            }
        });
        jPanel5.add(bsimpans, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, -1));

        bubahs.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bubahs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_30px.png"))); // NOI18N
        bubahs.setText("Ubah");
        bubahs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahsActionPerformed(evt);
            }
        });
        jPanel5.add(bubahs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        bhapuss.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bhapuss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hapus_30px.png"))); // NOI18N
        bhapuss.setText("Hapus");
        bhapuss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapussActionPerformed(evt);
            }
        });
        jPanel5.add(bhapuss, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        bbatals.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bbatals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cancelit_30px.png"))); // NOI18N
        bbatals.setText("Batal");
        bbatals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalsActionPerformed(evt);
            }
        });
        jPanel5.add(bbatals, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        bkeluars.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        bkeluars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exitsign_30px.png"))); // NOI18N
        bkeluars.setText("Keluar");
        bkeluars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarsActionPerformed(evt);
            }
        });
        jPanel5.add(bkeluars, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 130, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/HOME.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsupplierMouseClicked
        // TODO add your handling code here:
        int bar=tblsupplier.getSelectedRow();
        String a = tabmode.getValueAt(bar,0).toString();
        String b = tabmode.getValueAt(bar,1).toString();
        String c = tabmode.getValueAt(bar,2).toString();
        String d = tabmode.getValueAt(bar,3).toString();

        txtids.setText(a);
        txtnms.setText(b);
        txthps.setText(c);
        txtalamats.setText(d);
    }//GEN-LAST:event_tblsupplierMouseClicked

    private void txtcarisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarisKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcarisKeyPressed

    private void bcarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcarisActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcarisActionPerformed

    private void bsimpansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpansActionPerformed
        // TODO add your handling code here:
        String sql = "insert into supplier values (?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,txtids.getText());
            stat.setString(2,txtnms.getText());
            stat.setString(3,txthps.getText());
            stat.setString(4,txtalamats.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            autonumber();
            txtnms.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
        }
        datatable();
    }//GEN-LAST:event_bsimpansActionPerformed

    private void bubahsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahsActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "update supplier set nmsupplier=?,nohps=?,alamats=? where idsupplier ='"+txtids.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,txtnms.getText());
            stat.setString(2,txthps.getText());
            stat.setString(3,txtalamats.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            kosong();
            autonumber();
            txtnms.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahsActionPerformed

    private void bhapussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapussActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda Yakin Untuk Menghapus","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "delete from supplier where idsupplier ='"+txtids.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                autonumber();
                txtnms.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapussActionPerformed

    private void bbatalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalsActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
        autonumber();
    }//GEN-LAST:event_bbatalsActionPerformed

    private void bkeluarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarsActionPerformed
        // TODO add your handling code here:
        dispose();
        new start.home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bkeluarsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supllier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supllier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supllier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supllier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new supllier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatals;
    private javax.swing.JButton bcaris;
    private javax.swing.JButton bhapuss;
    private javax.swing.JButton bkeluars;
    private javax.swing.JButton bsimpans;
    private javax.swing.JButton bubahs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblsupplier;
    private javax.swing.JTextArea txtalamats;
    private javax.swing.JTextField txtcaris;
    private javax.swing.JTextField txthps;
    private javax.swing.JTextField txtids;
    private javax.swing.JTextField txtnms;
    // End of variables declaration//GEN-END:variables
}
